### ISSUE TITLE
arg "RightIndexName" is useless in svd of IQTensor

### ISSUE THREAD

**Issue by xichuang** [ITensor/ITensor#112]
This does not matter much. 
But I think there is a misstype in line 284 of itenosr/svd.cc. 
It should be
`auto R = IQIndex(rname,move(Riq),vI.dir());`
rather than
`auto R = IQIndex(lname,move(Riq),vI.dir());`

Thank you.

**Comment by emstoudenmire** [comment]
Fixed. Thanks!
