### ISSUE TITLE
Trouble with itensor::showtime

### ISSUE THREAD

**Issue by Wuggins** [ITensor/ITensor#114]
A short program I have (mostly just running DMRG) refuses to compile now with blas/lapack.

![capture](https://cloud.githubusercontent.com/assets/5287712/21124705/5b668458-c095-11e6-96c5-f08c30839c2f.PNG)

**Comment by Wuggins** [comment]
Update: the same code works just fine on my other computer with intel mkl.

**Comment by emstoudenmire** [comment]
Hi Bill, 
Thanks for the bug report! You are right: there was a spurious "inline" flag on a function that shouldn't have been there. Probably the compiler on your MKL computer was just not as picky about it, but technically it was a bug. Hopefully with patch b9c0fbb0fd4ec311f728db it should now be fixed.

**Comment by emstoudenmire** [comment]
Please reopen the bug if it still doesn't compile on the first computer you tried - thanks.
