### ISSUE TITLE
Something strange (perhaps to do with getting an element from a const ITensor??) that won't let me compile one on box (but works fine with Intel MKL)

### ISSUE THREAD

**Issue by Wuggins** [ITensor/ITensor#115]
Hi Miles,

I have some code that compiles just fine on the cluster with the MKL library and gcc-4.9.3 but won't compile on my laptop. I copied and pasted the terminal output here:

![image](https://cloud.githubusercontent.com/assets/5287712/21443278/ab844b44-c858-11e6-8234-5a30b6c176a4.png)

Thanks for your help!!

- Bill

**Comment by emstoudenmire** [comment]
Thanks Bill. The error message seems to be that it can't find the definition of std::complex<double>. So probably there is an #include statement needed somewhere that is missing. (Sometimes I rely on a particular #include to pull in other headers files that I don't list explicitly, but which other headers get pulled in can vary across different standard library implementations.)

Can you try putting #include <complex> at the top of your program (or in a header file that most of your code uses)? If that fixes it, it means I need to put #include <complex> somewhere in ITensor.
