### ISSUE TITLE
IQIndex cannot work with  writeToFile.

### ISSUE THREAD

**Issue by xichuang** [ITensor/ITensor#116]
The IQIndex cannot work with 
writeToFile("link", link);
Here link is an IQIndex object.
There is an error of "Object does not define .write method".

I use the latest git version of ITensor.
Is it a bug?

Thank you.

**Comment by emstoudenmire** [comment]
Hi, I see that you closed this, but let me know if the issue persists for you. I just checked and at least on my system I can write IQIndex objects to disk using writeToFile.

**Comment by xichuang** [comment]
I'm sorry to disturb you.
I reported this issue because I was trying to save a vector of IQIndex directly.
Write a single IQIndex object to disk do works.

**Comment by emstoudenmire** [comment]
Ok no problem. Glad you reported it - always good to check these things.
