### ISSUE TITLE
MPO has no setA due to private inheritance of MPS

### ISSUE THREAD

**Issue by martenrichter** [ITensor/ITensor#126]
Hi,
a student of mine is playing around with iTensor for applications, that are not using spin chains.
Therefore we try to avoid SiteSet objects, since they use IQIndex and we need the general Index class and just setting plain ITensor for the sites.
In order to use and initialize the MPS and MPO objects, we like to use the setA function.
It works fine with MPS, but MPO inherits MPS privately, so that the setA is not accessible.
As a workaround, we change the private keyword in mpo.h to public. 
Do you think there will be any problems, if we use the setA function with MPO? What is the reason for using private inheritance?
Thank you in advance for your answer!

Marten

**Comment by emstoudenmire** [comment]
Hi Marten,
Thanks for pointing this out. I just pushed a new version that makes the setA method for MPO and IQMPO available (I added a using Parent::setA; statement). 

By the way, SiteSets can be used for other kinds of systems besides spin chains. There are site sets for fermion systems, for example, and it's easy to define your own for other kinds of systems. Also the 1D ordering inherent to a site set doesn't mean it's limited to 1D; they are useful with 2D DMRG also. But if you are doing a truly 2D application, such as PEPS, then a site set might be too limiting in how it works. Please let me know by email if you have any questions about this.

The reason for using private inheritance is that I only wanted some of the MPS methods available for MPOs. Not all of the MPS methods make sense for MPOs. Another way I could have done this would have been not to have MPO inherit from MPS but rather contain an MPS internally. But the inheritance approach has some benefits. There's no perfect solution; really inheritance is not such an ideal approach for most things. In a nicer language than C++ one could have better control over template functions and better support for generic programming overall, and favor a more generic functional style over object oriented. Just my 2 cents. But C++ is still our best option for many other reasons. Do let me know if you see a better possible design here.
