### ISSUE TITLE
Implicit sign change

### ISSUE THREAD

**Issue by markusschmitt** [ITensor/ITensor#130]
Hi Miles,

in ITensor v2.1.0 I found that for an ITensor `A` writing `-A` changes the sign of A, i.e. the code line `-A;` has the  effect one would expect from the code line `A=-A;`. I am not sure whether this is intended, as it leads to surprising side effects, e.g. the line `C=-A*B;` also leaves A with the inverted sign.

Here is a minimal example to demonstrate this behaviour:
```
#include "itensor/all.h"
using namespace itensor;
int main(int argc, char* argv[]) {
    Index i("i",2);
    Index j("i",2);
    ITensor A(i,j);
    A.set(i(1),j(2),1);
    PrintData(A);
    -A;
    PrintData(A);
}
```
This produces the output
```
A = 
ITensor r=2: (i,2,Link|45) (i,2,Link|210)
{log(scale)=0.00, norm=1.00 (Dense Real)}
(1,2) 1.0000000

A = 
ITensor r=2: (i,2,Link|45) (i,2,Link|210)
{log(scale)=0.00, norm=1.00 (Dense Real)}
(1,2) -1.000000
```

Best,
Markus

**Comment by emstoudenmire** [comment]
Thanks for the bug report! It was indeed an incorrect definition of the negation operator. I added a unit test also so this bug can't occur the same way in the future.

Also I added your name to our contributors list: http://itensor.org/about.html
