### ISSUE TITLE
Problem in overlap function with 2 mpos and 2 mps

### ISSUE THREAD

**Issue by martenrichter** [ITensor/ITensor#135]
Hi Milea,
I am sorry for disturbing again. 
Today, we run into a problem with the overlap function, which took us sometime to investigate.
We are applying an non hermitian MPO to an MPS and we wanted to calculate the norm of the result.
Unfortunately, the overlap function does not do, what it is expected to do. It is either a bug, or false documentation.
So the overlap function (and the overlapC counterpart) is declared as:
```
template <class Tensor>
void
overlap(MPSt<Tensor> const& psi, 
        MPOt<Tensor> const& H, 
        MPOt<Tensor> const& K,
        MPSt<Tensor> const& phi, 
        Real& re, 
        Real& im) //<psi|H K|phi>
{
```
Because of the comment <psi|H K|phi>, I expected, that it calculates <psi|H K|phi>. (Which would be the logical way for this interface, since psi is taken as adjunct.
But because of:
```
MPOt<Tensor> Kp(K);
Kp.mapprime(1,2);
Kp.mapprime(0,1);
```
it actually calculates: <psi|K H|phi> .
This is a big difference, if you try to calculate <psi|A^\dagger A|psi>  (and may take some time to realize, what is going on).
I see two ways to fix this:

1.  You can just change the comment //<psi|H K|phi> to //<psi|K H|phi> .
Advantages it is easy and does not break the interface, but the interface is not really logical. 
2. You correct the code to match the description (but requires a lot of exchanging K and H's), it will be a logical interface, but it may break older code.

Marten

**Comment by emstoudenmire** [comment]
Hi Martin,
No problem - thanks for bringing this to my attention. Another user recently reported this bug, so I am working to fix it and am almost done (things have been slow recently since I just wrapped up a cross-country move). 

I'll post the patch soon to fix this -

Thanks,
Miles
