### ISSUE TITLE
Error when using visit() function to diagonal tensor.

### ISSUE THREAD

**Issue by xichuang** [ITensor/ITensor#136]
Hi Miles
Recently I upgrade itensor to the most recent version via git. After running the code
`D.visit(maxAbs)`
,I got the following error:

_terminate called after throwing an instance of 'itensor::ITError'
what(): doTask not defined for task VisitIT and storage type DiagReal_

where D is the diagonal tensor outputted by `diagHermitian(A, W, D);`.

I guess the visit function for diagonal tensor is broken in the current version.
If this is supposed to be, I wonder if there exist another way to visit the diagonal tensor.

Thank you.

**Comment by emstoudenmire** [comment]
Hi, thanks for the bug report. This feature was indeed missing. For some of the sparse tensor types I have been taking a more conservative approach when it comes to defining various features, just to make sure there is a need for them. I just pushed a commit that adds this feature for DiagReal and DiagCplx storage. Please let me know if it still doesn't work for some reason.
