### ISSUE TITLE
Extract the Storage of a Dense ITensor with wrong values

### ISSUE THREAD

**Issue by empter** [ITensor/ITensor#139]
Hi Miles,
In page http://itensor.org/docs.cgi?page=formulas/extractdense , you provide methods to extract the storage of a dense ITensor, and they works for most circumstances. But in some situation,  the unwraped data does not agree with the Tensor elements. is this a designed feature or bug?
Here is the test code:
```
#include "itensor/all_basic.h"

using namespace itensor;

struct ExtractReal {};
std::vector<Real>
doTask(ExtractReal, Dense<Real> const& d)
{
  return d.store;
}

int main()
    {
      auto b0 = Index("bond0",2);
      auto b0p = prime(b0);
      auto T = randomTensor(b0,b0p);
      T *= 10;
      PrintData(T);
      auto mat = doTask(ExtractReal{},T.store());
      for(unsigned i = 0; i < mat.size(); ++i) PrintData(mat[i]);

return 0;
}
```
the output is:

> T = 
ITensor r=2: ("bond0",2,Link|878) ("bond0",2,Link|878)'
{log(scale)=2.30, norm=10.94 (Dense Real)}
(1,1) 9.6266437
(2,1) 0.0861992
(1,2) 2.1367585
(2,2) 4.7287589
 

> mat[i] = 0.962664
mat[i] = 0.00861992
mat[i] = 0.213676
mat[i] = 0.472876

The mat = doTask(ExtractReal{},T.store()) returns a vector with each element 10 times smaller than those in T. In other situations, the elements in returned vector may be T/norm(T). In my opinion, the elements in mat and T should be equal.

Code was tested in both Mac and Bash on Windows with latest ITensor cloned from the repository.

**Comment by emstoudenmire** [comment]
Hi, thanks for the question. This is a designed feature. What is happening here is that this ITensor has a scale factor which is different from 1 (the scale factor can be accessed by calling .scale() on an ITensor or IQTensor). ITensors normally start out with a scale factor that is equal to 1., but then this can be changed after certain operations like adding or contracting tensors. The value of a specific tensor element is always defined as the product of that element in the storage times the scale factor.

If you take a look at the implementation of say, operator+= (adding two ITensors) on line 244 of itensor_operators.cc there is a factor computed from the relative scale factors of the two tensors that is passed with the PlusEq task object. Then this factor is used in the lower level addition routines, such as in itdata/dense.cc

Hope that helps -

Miles

**Comment by empter** [comment]
Thank you for pointing out the scale feature in ITensor. I think it's better to mention this feature in page http://itensor.org/docs.cgi?page=formulas/extractdense so anyone who want to directly access the storage of a Tensor (such as passing the storage to other library) will not confused.

**Comment by emstoudenmire** [comment]
That is a good suggestion. I added a note to that page.
