### ISSUE TITLE
FIX: Index mismatch during parallel computions 

### ISSUE THREAD

**Issue by fskovbo** [ITensor/ITensor#158]
Itensor index/ID mismatches occur randomly when running contracting networks in parallel. The issue is due to `static Index::IDGenerator` (in index.cc line 52) being shared among multiple threads.
The issue can be resolved by replacing the following line:

`static Index::IDGenerator G;` --> `static thread_local Index::IDGenerator G;`

This should make the IDGenerator thread-safe.

**Comment by emstoudenmire** [comment]
Thanks for the bug report. I recently pushed a patch in this commit a5305e49101d0c46aab410148cf506e024f3338d

Does it fix your issue? Please test it out by pulling and compilng the latest version & let me know. Thanks!

**Comment by emstoudenmire** [comment]
Great! Ok please reopen the issue if you run into any trouble in the future -
