### ISSUE TITLE
davidson() for ITensor and account on the discussion forum

### ISSUE THREAD

**Issue by titaschanda** [ITensor/ITensor#163]
Hi Miles,

Can I use ``davidson()`` function to obtain the low-lying eigenvectors corresponding to a ITensor, and a given initial guess, similar to ``diagHermitian`` function? Is it possible to do?

I was supposed to ask this question in the discussion (forum)[http://itensor.org/support/]. But I could not set up the account, as I did not get the confirmation mail. I have tried a few times, but it didn't help. Can you please help me in this regards too?

Thanking you,
Titas

**Comment by emstoudenmire** [comment]
Hi Titas, can you please send me an email for support questions like this? Also yes ideally you should use the forum so other people can see our discussion. I checked and the email you put was titas.chanda@gmail.com. If that's correct, then the verification should have arrived (a lot of other people recently registered successfully). Did you check your Spam folder? Maybe it is in there?

**Comment by titaschanda** [comment]
Ooops. The confirmation mail got stuck in the spam folder. Sorry. I will ask this question in the forum. I think, I found a solution, and I will append it with the question.

Thanking you,
Titas
