### ISSUE TITLE
Missing inline for findEig function?

### ISSUE THREAD

**Issue by markusschmitt** [ITensor/ITensor#203]
When trying to compile some code using the ITensor library, I got a duplicate symbol error for the findEig function defined in iterativesolvers.h on line 639. By defining this function as inline I could avoid this error. Is there a reason why it should not be inlined?

**Comment by mtfishman** [comment]
No reason, I just forgot to add `inline`. Thanks for pointing it out, I will push a fix! Unfortunately our unit tests don't seem to catch this...

**Comment by mtfishman** [comment]
I pushed a fix to master, let me know if you have other problems.
