### ISSUE TITLE
Change Index printing

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensor#216]
Instead of `("Site",2|id=231)'` it should print `(2|id=231|"Site")'` to make it clearer that the tags are temporary, like the prime level, but the id is permanent.

**Comment by emstoudenmire** [comment]
One step ahead of you there 😃 

See this commit: 64de72f287cc498d6c97a16eaa97d5d900ba72cb

**Comment by mtfishman** [comment]
I guess I haven't pulled in a while!
