### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by jsf15** [ITensor/ITensor#223]
Hi,

I was setting up the latest RC3 commit but after installing without errors, an error occurs when calling ITensor `#include "itensor/all.h"`

I've tried calling `#include "itensor/indexset.h" #include "itensor/all.h"` but that didn't solve the problem. Any suggestions on why this is happening?

> 
> /usr/bin/ld: tests.o: in function `void itensor::println<itensor::IndexSet, char const (&) [2], void>(itensor::IndexSet const&, char const (&) [2])':
> tests.cc:(.text._ZN7itensor7printlnINS_8IndexSetEJRA2_KcEvEEvRKT_DpOT0_[_ZN7itensor7printlnINS_8IndexSetEJRA2_KcEvEEvRKT_DpOT0_]+0x17): undefined reference to `itensor::operator<<(std::ostream&, itensor::IndexSet const&)'
> /usr/bin/ld: /home/joaosf/itensor/lib/libitensor.a(combiner.o): in function `void itensor::println<char [29], itensor::IndexSet const&, void>(char const (&) [29], itensor::IndexSet const&)':
> combiner.cc:(.text._ZN7itensor7printlnIA29_cJRKNS_8IndexSetEEvEEvRKT_DpOT0_[_ZN7itensor7printlnIA29_cJRKNS_8IndexSetEEvEEvRKT_DpOT0_]+0x2d): undefined reference to `itensor::operator<<(std::ostream&, itensor::IndexSet const&)'
> /usr/bin/ld: /home/joaosf/itensor/lib/libitensor.a(combiner.o): in function `void itensor::println<char [31], itensor::IndexSet const&, void>(char const (&) [31], itensor::IndexSet const&)':
> combiner.cc:(.text._ZN7itensor7printlnIA31_cJRKNS_8IndexSetEEvEEvRKT_DpOT0_[_ZN7itensor7printlnIA31_cJRKNS_8IndexSetEEvEEvRKT_DpOT0_]+0x2d): undefined reference to `itensor::operator<<(std::ostream&, itensor::IndexSet const&)'
> /usr/bin/ld: /home/joaosf/itensor/lib/libitensor.a(combiner.o): in function `void itensor::println<char [30], itensor::IndexSet const&, void>(char const (&) [30], itensor::IndexSet const&)':
> combiner.cc:(.text._ZN7itensor7printlnIA30_cJRKNS_8IndexSetEEvEEvRKT_DpOT0_[_ZN7itensor7printlnIA30_cJRKNS_8IndexSetEEvEEvRKT_DpOT0_]+0x2d): undefined reference to `itensor::operator<<(std::ostream&, itensor::IndexSet const&)'
> /usr/bin/ld: /home/joaosf/itensor/lib/libitensor.a(combiner.o): in function `void itensor::println<char [32], itensor::IndexSet const&, void>(char const (&) [32], itensor::IndexSet const&)':
> combiner.cc:(.text._ZN7itensor7printlnIA32_cJRKNS_8IndexSetEEvEEvRKT_DpOT0_[_ZN7itensor7printlnIA32_cJRKNS_8IndexSetEEvEEvRKT_DpOT0_]+0x2d): undefined reference to `itensor::operator<<(std::ostream&, itensor::IndexSet const&)'
> /usr/bin/ld: /home/joaosf/itensor/lib/libitensor.a(itensor.o):itensor.cc:(.text+0x21bf): more undefined references to `itensor::operator<<(std::ostream&, itensor::IndexSet const&)' follow
> collect2: error: ld returned 1 exit status
> make: *** [Makefile:42: tests] Error 1
>

**Comment by jsf15** [comment]
I'm not sure if it's important but when running make debug no error occurs

**Comment by mtfishman** [comment]
Did you try recompiling the ITensor library itself, i.e. go to your base itensor directory and type `make clean && make`?

**Comment by jsf15** [comment]
yes, and I've also try going to some other branch and coming back with --hard. Running with debug works like a charm

**Comment by mtfishman** [comment]
Do the ITensor unit tests pass?

**Comment by jsf15** [comment]
I think so, it's the last sentence right?

From https://github.com/ITensor/ITensor
 * branch              rc3        -> FETCH_HEAD
Updating 71c4bb81..9bb49c1f
Fast-forward
 V3_ROADMAP                          |  21 ++-
 itensor/decomp.h                    |   4 +-
 itensor/global.h                    |   2 +-
 itensor/hermitian.cc                |   1 -
 itensor/indexset.cc                 |  70 +++++----
 itensor/indexset.h                  |  84 ++++++-----
 itensor/indexset_impl.h             |   9 +-
 itensor/itdata/combiner.cc          |   2 +-
 itensor/itdata/dense.cc             |   2 +-
 itensor/itdata/diag.cc              |   2 +-
 itensor/itdata/qcombiner.cc         |   2 +-
 itensor/itdata/qdense.cc            |   2 +-
 itensor/itdata/qdiag.cc             |   4 +-
 itensor/itensor.cc                  |  52 +++++--
 itensor/itensor.h                   |  16 +++
 itensor/iterativesolvers.h          |   2 +-
 itensor/mps/mpo.cc                  | 313 ++++++++++++++++++++--------------------
 itensor/mps/mpo.h                   | 100 ++++++-------
 itensor/mps/mpoalgs.cc              | 114 +++++++++++----
 itensor/mps/mps.cc                  | 215 +++++++++++-----------------
 itensor/mps/mps.h                   | 171 +++++++++++++++-------
 itensor/mps/mps_impl.h              | 139 +++++++++++++++---
 itensor/mps/mpsalgs.cc              |  23 +--
 itensor/tagset.cc                   |  10 +-
 itensor/tensor/algs.cc              |   2 +-
 itensor/tensor/contract.h           |   2 +-
 itensor/tensor/mat.cc               |   2 +-
 itensor/tensor/sliceten.h           |   2 +-
 itensor/util/{range.h => iterate.h} |   9 +-
 itensor/util/itertools.h            | 333 +++++++++++++++++++++++++++++++++++++++++++
 unittest/contract_test.cc           |   2 +-
 unittest/itensor_test.cc            |   2 +-
 unittest/matrix_test.cc             |   2 +-
 unittest/mpo_test.cc                | 377 ++++++++++++++++++++-----------------------------
 unittest/mps_mpo_test_helper.h      |  81 +++++++++++
 unittest/mps_test.cc                | 384 ++++++++++++++++++++++++--------------------------
 unittest/sparse_contract_test.cc    |   2 +-
 unittest/tensor_test.cc             |   2 +-
 38 files changed, 1586 insertions(+), 976 deletions(-)
 rename itensor/util/{range.h => iterate.h} (92%)
 create mode 100644 itensor/util/itertools.h
 create mode 100644 unittest/mps_mpo_test_helper.h

**Comment by mtfishman** [comment]
That list is just a list of files that were added or updated when you pulled the new commit (it is the output of the `git pull` command). After you pull the changes, you have to recompile the ITensor library. So could you please do:
```
$ cd /home/joaosf/itensor
$ make clean
$ make
```
Once it compiles, could you then do:
```
$ cd unittest
$ make
```
After that command, it should compile all of the tests in `unittest`, and then run them. You should see an output `Running all tests...` to show the tests compiled and are running, and then something like `All tests passed (178581 assertions in 33 test cases)` (the exact number may be different).

Please let me know if that works for you!

Cheers,
Matt

**Comment by mtfishman** [comment]
Actually, would you mind opening a support question about this on the ITensor support page (http://www.itensor.org/support/)?

We would prefer to keep the Github issue page for bug reports, feature requests, etc. I think compilation issues fit better over there.

Thanks!
-Matt

**Comment by jsf15** [comment]
Sorry about the confusion. I get `All tests passed (178570 assertions in 33 test cases)` which is not surprising since the tests are running with debug mode
