### ISSUE TITLE
AutoMPO does not handle J-W String properly in v3 branch

### ISSUE THREAD

**Issue by empter** [ITensor/ITensor#243]
hi,

It seems that the AutoMPO class does not insert Jordan-Wigner String in Fermion systems properly, here is a test code
```
#include "itensor/all.h"
using namespace itensor;

int main()
    {
      auto N = 2;
      auto sites = Fermion(N);
      auto ampo = AutoMPO(sites);
      auto t = 0.5;
      for(auto b : range1(N-1))
          {
          ampo += -t,"Cdag",b,"C",b+1;
          ampo += -t,"Cdag",b+1,"C",b;
          }
      auto H = toMPO(ampo,{"Exact",true});
      PrintData(H);
    }
```

The output reads
```
Hx = 

ITensor ord=3: 
(2|id=522|n=1,Site,Fermion) <In>
  1: 1 QN()
  2: 1 QN({"Nf",1})
(2|id=522|n=1,Site,Fermion)' <Out>
  1: 1 QN()
  2: 1 QN({"Nf",1})
(4|id=637|l=1,Link) <Out>
  1: 2 QN()
  2: 1 QN({"Nf",-1})
  3: 1 QN({"Nf",1})
QDense Real {4 blocks; data size 6}
Block: 1 1 1
(1,1,1) 1.0000000
Block: 2 2 1
(2,2,1) 1.0000000
Block: 1 2 2
(1,2,3) 1.0000000
Block: 2 1 3
(2,1,4) 1.0000000
```
but the last line should be `(2,1,4) -1.0000000`.

ps: the master branch(v2) reproduce spinless sites MPO correctly.

**Comment by emstoudenmire** [comment]
Hi, I'm not sure if that output is correct or not because it is only one of the two MPO tensors produced by the toMPO function. Could you please check that the MPO is correct this way: multiply both tensors back together to get the full Hamiltonian tensor which should have 4 site indices (two unprimed; two primed). Then check that it has the correct matrix elements?

**Comment by empter** [comment]
Hi, Miles

here is a new test example which reproduce wrong result for fermion system.

```
int main()
    {
      auto N = 2;
      auto sites = Fermion(N);
      auto ampo = AutoMPO(sites);
      auto t = 0.5;
      for(auto b : range1(N-1))
          {
          ampo += -t,"Cdag",b,"C",b+1;
          ampo += -t,"Cdag",b+1,"C",b;
          }
      auto H = toMPO(ampo,{"Exact",true});
      PrintData(H(1)*H(2));
      auto state = InitState(sites,"Emp");
      state.set(1,"Occ");
      auto psi = MPS(state);
      PrintData(H(1)*H(2)*psi(1)*psi(2));
    }
```
the output reads
```
H(1)*H(2) = 
ITensor ord=4: 
(2|id=35|n=1,Site,Fermion) <In>
  1: 1 QN()
  2: 1 QN({"Nf",1})
(2|id=35|n=1,Site,Fermion)' <Out>
  1: 1 QN()
  2: 1 QN({"Nf",1})
(2|id=822|n=2,Site,Fermion) <In>
  1: 1 QN()
  2: 1 QN({"Nf",1})
(2|id=822|n=2,Site,Fermion)' <Out>
  1: 1 QN()
  2: 1 QN({"Nf",1})
QDense Real {6 blocks; data size 6}
Block: 1 2 2 1
(1,2,2,1) -0.500000
Block: 2 1 1 2
(2,1,1,2) 0.5000000

H(1)*H(2)*psi(1)*psi(2) = 
ITensor ord=2: 
(2|id=35|n=1,Site,Fermion)' <Out>
  1: 1 QN()
  2: 1 QN({"Nf",1})
(2|id=822|n=2,Site,Fermion)' <Out>
  1: 1 QN()
  2: 1 QN({"Nf",1})
QDense Real {2 blocks; data size 2}
Block: 1 2
(1,2) 0.5000000
```

`H|psi>=-t(Cdag_1 C_2+Cdag_2 C_1)|10>=-t|01>` but the program gives `t|01>`, the MPO block `Block: 2 1 1 2 (2,1,1,2) 0.5000000` omit a minus sign.

I find this problem because unittest/autompo_test failed in SECTION("Fermion")

**Comment by emstoudenmire** [comment]
Thanks again for the bug report. The bug turned out to be an improper QN definition in the Fermion site set, combined with a new way of handling Jordan-Wigner string in the op function. So I fixed the Fermion site set to define the QN properly and now it works. Best regards, Miles
