### ISSUE TITLE
A suggestion about the prime() function

### ISSUE THREAD

**Issue by hyx15903** [ITensor/ITensor#248]
Hi all,

The current prime(itensor, args) function doesn't seem to support combinations of TagSets and IndexSets anymore in v3, where in v2 I could use prime(itensor, Tags, Index). I think it would be helpfull to add this function in v3.

**Comment by mtfishman** [comment]
Hi, sorry for the later response.

Could you please give me your use case for that? I don't doubt that it is useful, but it is good to have a concrete example of where it is used to figure out the best solution. 

One thing you can consider is that the following should work:

```C++
auto i = Index(2,"i,Link");
auto j = Index(2,"j,Link");
auto k = Index(2,"k,Site");
auto l = Index(2,"l,Site");

auto A = randomITensor(i,j,k,l);

// prime Indices i,j,k
A.prime({findInds(A,"Link"), k});
// Or just do: A.prime("Link").prime(k);
```

Another thing to consider is that if you are often priming those indices as a group, you could think about adding a common tag to all of them, i.e.:

```C++
auto i = Index(2,"i,Link,x");
auto j = Index(2,"j,Link,x");
auto k = Index(2,"k,Site,x");
auto l = Index(2,"l,Site");

auto A = randomITensor(i,j,k,l);

// prime Indices i,j,k
A.prime("x");
```

Part of the goal of the new tag design, as well as an addition of many new functions for dealing with IndexSets, was to simplify the set of prime functions. Many of the prime functions had different interfaces with complicated designs, which became very difficult to keep track of for users and developers. It has also allowed a more uniform interface for priming different ITensor objects, like IndexSets, ITensors, MPS and MPO (where the arguments need to be passed through a series of functions, which becomes more difficult if we allow mixtures of arbitrary lists of tagsets and indices as inputs).

**Comment by hyx15903** [comment]
I think you are right, there are other easy ways to prime an itensor with both tags and index, like you mentioned above. The case that I am working on is that I want to calculate a two-site correlation function for a certain MPS, so I would do
...
auto ir = commonIndex(psi(x1), psi(x1 + 1));
auto C = psi(x1) * op_ap * dag(prime(psi(x1), "Site", ir));
...
Thank you for providing a good example of it.
