### ISSUE TITLE
Bug in diagITensor constructor

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensor#256]
```C++
auto i = Index(QN(-1),2,QN(+1),2,"i");
auto j = Index(QN(-1),2,QN(0),2,"j");

auto v = vector<Real>({1.0,2.0,3.0,4.0});
auto A = diagITensor(v,i,dag(j));
```
This creates a very strange tensor that doesn't have a well defined QN flux and has Diag (not QDiag) storage. Maybe this constructor wasn't meant to be used with QNs?

**Comment by mtfishman** [comment]
I added a check in `diagITensor` to see that only non-QN Indices are passed, otherwise it throws an error. We can think of a proper `diagITensor` constructor for QN-indices later.

**Comment by emstoudenmire** [comment]
Haven’t looked at this constructor in a while, but yes I think it was just an oversight to allow it to take QN indices.
