### ISSUE TITLE
Is there a mistake in Trotter error in the TEBD code formula in ITensor website ?

### ISSUE THREAD

**Issue by orialb** [ITensor/ITensor#271]
Hi,

I think there might be a mistake in the [TEBD code formula](http://itensor.org/docs.cgi?vers=cppv3&page=formulas/tevol_trotter) in the order of the Trotter error. 
It's written there that the error is O(\tau^2) per time-step, but I think what you are showing there is a form of a 2nd order Trotter decomposition so the error should be O(\tau^3)  per time-step and O(t \tau^2) for the whole evolution. 
See Eq. (4) and discussion below it in https://journals.aps.org/prl/pdf/10.1103/PhysRevLett.93.076401 . 
Or am I missing something?

**Comment by emstoudenmire** [comment]
Hi yes, I checked that paper and another reference and the website is in error. So I'll fix it asap - thanks very much!
