### ISSUE TITLE
Small args bug

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensor#281]
This was pointed out be Daniel:

```
  auto i = Index(2,"i");
  auto A = randomITensor(i,prime(i));

  // Errors
  std::string s = "LeftTags";
  
  // Works
  //auto s = "LeftTags";

  auto [U,S,V] = svd(A,{i},{s,"TEST"});
```

I guess for the argument name, right now it only accepts char arrays, not std::string.

**Comment by emstoudenmire** [comment]
Thanks! I should discuss with Daniel what he is wanting to do here, because this usage is outside of the intended use of args (at least the usage I envisioned). It's meant to mimic keyword args in python or Julia, where you also cannot use a variable in place of an explicit keyword arg name.

**Comment by mtfishman** [comment]
Yes, I agree that it is not necessarily how the args system should be used anyway. The use case was basically the following:

```
  auto s = Index(2,"Site");
  auto l = Index(2,"Link,l");
  auto r = Index(2,"Link,r");
  auto A = randomITensor(l,r,s);

  auto sweepDir = "FromLeft";
  
  auto s = "LeftTags";
  if(sweepDir == "FromRight")
    s = "RightTags";

  auto [U,S,V] = svd(A,{l,s},{s,"NewTag"});

  // U becomes the new gauged MPS tensor
  // S*V incorporated into the next MPS tensor
```

so basically, it is a custom `svdBond` function where you want to set the tags of the new link properly.

I already suggested other ways of doing what he wanted to do, for example just setting both "LeftTags" and "RightTags", or inputing `{r,s}` as the indices if sweeping from the right.

**Comment by emstoudenmire** [comment]
Great. Also, a good way to handle this case could be:

```
Args args;
if(sweepDir == "FromRight") 
    args.add("RightTags","NewTag");
else                                          
    args.add("LeftTags","NewTag");
auto [U,S,V] = svd(A,{l,s},args);
```

But I can see why he missed that because the `.add` feature of Args is not well documented. (Which reminds me I've been meaning to split Args off as its own separate library for some time.)

**Comment by mtfishman** [comment]
Oh yes good point, that is a good way to do it.
