### ISSUE TITLE
Truncate zero singular values

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensor#290]
This is an issue brought up by Daniel when trying to truncate an MPO. Right now, if {"Cutoff=",0.} and there are singular values that are exactly zero, they are not truncated. For example:
```C++
  auto i = Index(2,"i");
  auto A = randomITensor(i,prime(i));
  auto [Q,P] = polar(A,{i});
  Q.mapPrime(2,1);
  auto D = ITensor(i,prime(i));
  D.set(1,1,1.);
  auto H = Q*prime(D)*dag(prime(Q));
  auto [U,S,V] = svd(H,{i},{"Cutoff=",0.});

  PrintData(U);
  PrintData(S);
  PrintData(V);
```
gives a dimension of 2, while I would expect it should be 1. If you set any finite value (i.e. {"Cutoff=",1E-50}) it truncates to dimension 1. This can be significant when it involves truncating an MPO where certain terms are exactly zero.

**Comment by mtfishman** [comment]
I realized that even if we had this, it may not be entirely reliable, since "zero" singular values could end up as very small finite values (this actually happens randomly in the case above with the current ITensor svd). So I think the better solution is to use a very small finite cutoff.

**Comment by emstoudenmire** [comment]
Good point. But I still think we could tweak the code behavior such that if the cutoff is 0.0 (exactly) and some of the eigenvalues are also 0.0 exactly, then those do get truncated. This could at least prevent the code from behaving in a surprising way. Or is there still a case that would be missed or be confusing?

**Comment by mtfishman** [comment]
I guess my conclusion from the above case giving stochastic results was that it didn't seem like a feature that should be relied on. But maybe it is still useful to be able to really specify that you don't want zero singular values, and this is the best interface to do that. I am ok with going ahead with it (it is just a matter of changing the `truncate` function to truncate values less than or equal to the cutoff instead of the less than the cutoff, I had already implemented it).

**Comment by mingruyang** [comment]
The denmatdecomp has the same problem. I was wondering if this commit will also fix it?

**Comment by mtfishman** [comment]
Yes it should, let us know if it doesn't.
