### ISSUE TITLE
Bug in denmatDecomp

### ISSUE THREAD

**Issue by titaschanda** [ITensor/ITensor#345]
I believe there is a bug in denmatDecomp, which throws segfault when called via .svdBond. Below, I attach a test code.

      int N = 100;
      auto sites = SpinHalf(N, {"ConserveQNs", false});  

      vector<MPS> psis;

      for (int dummy = 0; dummy < 30; ++dummy)
        psis.emplace_back(randomMPS(sites));
  
      auto psi = sum(psis);
      psi.normalize();

     psi.position(10);
     auto AA = psi(10) * psi(11);

     // calls denmatDecomp, setting noise to zero would work
     auto spec = psi.svdBond(10, AA, Fromleft, {"Noise", 1e-4, "Cutoff", 1e-13, "MaxDim", 10});

     cout << spec.truncerr() << endl;

**Comment by emstoudenmire** [comment]
Thanks! Will take a look
