### ISSUE TITLE
Sparsity of Input Tensors in /sample/hubbard_2d.cc or dmrg.cc with ConserveQNs Enabled

### ISSUE THREAD

**Issue by jiawen11** [ITensor/ITensor#350]
Hi,

When I configured "ConserveQNs" parameter in /sample/hubbard_2d.cc or dmrg.cc to enable block-sparse tensor computation, how to evaluate the "sparsity" in the tensor computation? (The "sparsity" means the percentage of the number of non-zero value to the total number of value. For example, a tensor with one non-zero value and ten thousand zero value, such that the "sparsity" is 1 /10000 = 0.0001) 

Also, is there any approach to control the "sparsity" of the generated input tensor for hubbard_2d and dmrg?

Any comments are welcome!

Thanks!

**Comment by emstoudenmire** [comment]
Answered by Matt Fishman in this Support Forum post:
http://itensor.org/support/2055/sparsity-input-tensors-sample-hubbard_2d-conserveqns-enabled
