### ISSUE TITLE
range1 not working like python

### ISSUE THREAD

**Issue by chuffa** [ITensor/ITensor#361]
I make quite a heavy usage of the range1() functionality and found that it does not work as I would expect it to when `e` is less than `b`. For example `for(auto i : range1(3,0) )` just keeps counting upwards instead of doing nothing.

Python ranges work differently and I think the idea of these c++ ranges is to mimic the python behavior. In any case, trying to make such a range should at least be caught somehow.

As far as I understand only line 57 of iterate.h needs changing by replacing != by <= (maybe >= too many negations):
https://github.com/ITensor/ITensor/blob/92f3936754a6ef15e1b65c8fa492a83321438a51/itensor/util/iterate.h#L57

**Comment by mtfishman** [comment]
Thanks for the report, I noticed this behavior as well. We would be happy to get a PR with a fix.

-Matt

**Comment by mtfishman** [comment]
Closed by #362.
