### ISSUE TITLE
extract dense ITensor storage

### ISSUE THREAD

**Issue by shencebebetterme** [ITensor/ITensor#375]
In the [documentation](http://itensor.org/docs.cgi?page=formulas/extractdense), it's expected that applying `extractReal` to `T.store()`  returns a `std::vector<Real>`.

However, a type conversion error occurs if I try to initialize a standard vector with the returned value `v`:
```
auto extractReal = [](Dense<Real> const& d)
    {
    return d.store;
    };

auto v = applyFunc(extractReal,T.store());

std::vector<Real> vec = v;
```

The compiler tells me the type of `v` is
```
stdx::conditional_t<false, stdx::remove_reference_t<itensor::detail::FuncHolder<type &> &&>, stdx::conditional_t<true, stdx::result_of_t<itensor::detail::TestRet<itensor::detail::FuncHolder<type &>, itensor::frontType<itensor::StorageTypes>> ()>, stdx::conditional_t<false, stdx::result_of_t<itensor::detail::TestRet<itensor::detail::FuncHolder<type &>, itensor::frontType<itensor::popFront<itensor::popFront<itensor::popFront<itensor::popFront<itensor::popFront<itensor::popFront<itensor::popFront<itensor::popFront<itensor::popFront<itensor::popFront<itensor::popFront<itensor::StorageTypes>>>>>>>>>>>>> ()>, itensor::NoneType>>>
```

This `v` has well-defined container properties, but it's not a standard vector.  The question is how to extract a standard vector from the tensor `T`?

**Comment by shencebebetterme** [comment]
I'm interested in this because I have found an expedient to bypass the arnoldi issue in #360.  

For those who need more matrix operations, you can compile ITensor together with other linear algebra packages such as [armadillo](http://arma.sourceforge.net/), and use the matrix functions therein. Below is an example of constructing an armadillo matrix from a rank-2 ITensor using the above `v`
```
    int di = 3;
    int dj = 3;
    auto i = Index(di, "i");
    auto j = Index(dj, "j");
    auto T = ITensor(i, j);
    T.randomize();

    auto extractReal = [](Dense<Real> const& d)
    {
    return d.store;
    };

    auto v = applyFunc(extractReal,T.store());

    arma::mat m(&v[0], di, dj, false);
```

**Comment by mtfishman** [comment]
ITensor storage makes use of an `std::vector` with a custom allocator that allows for allocating uninitialized memory (since `std::vector` always initializes memory as zeros, which we found to be a pretty significant cost throughout ITensor). You can see that [here](https://github.com/ITensor/ITensor/blob/v3/itensor/itdata/dense.h#L39), for example. You can see the definition [here](https://github.com/ITensor/ITensor/blob/fa5a50a60d252b3ba13677d7c109ed35f5fc2ae3/itensor/util/vector_no_init.h).

Perhaps you can use:
```
vector_no_init<Real> vec = v;
```
though I'm not sure if that will "play nice" with your application. Otherwise, you should be able to copy the data over to an `std::vector` using one of the many `std::vector` constructors or by copying the data over element by element, if you really need an `std::vector`.

**Comment by shencebebetterme** [comment]
Hi Matthew! Thanks a lot! 
I've read through the source codes of dense.h and vector_no_init.h and I can understand the implementation now.

**Comment by shencebebetterme** [comment]
After looking into the `ITData` class I've found a conceptually simpler and generally much faster (in debug mode) method to extract dense data to a `std::vector`. This is done in merely two lines.

```
vector_no_init<Real>& dvec = (*((ITWrap<Dense<Real>>*) & (*T.store()))).d.store;
	
std::vector<Real> vec(dvec.begin(), dvec.end());
```

The first line may look like a mess, but it's actually not very difficult to understand.

`T.store()` is a shared pointer to `ITData`, dereference it and take address again gives a bare pointer to `ITData`. The bare pointer is then converted to a pointer to the template class `ITWrap` which is derived from `ITData`.  For a Real dense ITensor this template parameter is the class `Dense<Real>`. Dereference this pointer again gives an `ITWrap` class, this is the type of the part inside the outermost bracket, so `(...)` has type `ITWrap`. 

The actual ITensor data is stored in a `Dense<Real>`,  the `d` member of  `ITWrap`.  Finally `(...).d.store` is a `std::vector` with a custom allocator, this is exactly the data vector that we want.

A standard vector can then be initialized by setting the correct iterators. This method is, in debug mode and on my laptop, around 70 times faster than the above `applyFunc` method, however, there's no performance difference in release mode. 

And there're more advantages since the data vector `dvec` is now completely exposed to us, for example it's easier to retrieve other information or even manipulate the data with STL tools, and not limited to `ITensor::visit` and `ITensor::apply`.
