### ISSUE TITLE
subscript out of range in itensor/util/autovector.h

### ISSUE THREAD

**Issue by shencebebetterme** [ITensor/ITensor#380]
Recently I'm trying to migrate the whole ITensor library and its dependencies to Windows system and build it with the native MSVC and Visual Studio. In doing so it's found that `PrintData(A)` gives a "subscript out of range" error.  This error is then traced back to the `end()` method of `autovector` class. This class is crucial to the data storage of an `ITensor`.
https://github.com/ITensor/ITensor/blob/c723d8976ddb076c7871414631952ef54c750891/itensor/util/autovector.h#L88

In "autovector.h", the length(number of elements) of the std::vector `dat_` is equal to `1+maxi_-mini_+miniloc_`, therefore in the expression `dat_[1+maxi_-mini_+miniloc_]` the subscript definitely goes out of range because the indexing is 0-based.

The `end()` thus obtained still points to the correct memory, however, the above behaviour is undefined and should be avoided. 

Previously this issue causes no warning/error because on Linux and on mac the element access by `[ ]` in a `std::vector` does not perform a bound check, and returns whatever in the memory as the out-of-range element. However, the MSVC implementation of `std::vector` does perform a bound check in debug mode, that's how I've found this issue.

Fixes are easy, just remove the `1+` inside `[ ]` and add the pointer by 1 unit instead. A pull request has been submitted.

**Comment by emstoudenmire** [comment]
Thanks for pointing this out and providing a PR to fix. I didn't appreciate that about the behavior of std::vector's `[ ]` operation on Windows.

I should add, though, that the storage of an ITensor does not depend on the `autovector` class. You may have seen some iterator code that uses similar names (.mini() and .maxi() for example) but this iterator code actually uses a different class called a `GCounter` (general counter) that is different from an `autovector`. It is a minor point, but I just wanted to add that information to clarify, or for anyone else who might be interested.

But `autovector` is a very useful concept and I think should be used more widely in C++ and other code!

**Comment by emstoudenmire** [comment]
Closed in #379
