### ISSUE TITLE
Bug: unexpected returning order of indexes

### ISSUE THREAD

**Issue by tanlin2013** [ITensor/ITensor#415]
Hi there,

I'm trying to understand the returning order of indexes that `AutoMPO()` produced, but it appears like there is an inconsistent behavior depending on the input argument `{"Exact=", true}` to the function `toMPO()`.

Below I give an example on constructing MPO for the 3-site tight-binding model. Depending on the argument `{"Exact=", true}`,  the MPO on first site (`n=1`) does not give a consistent behavior on the order of indexes. Note that it doesn't really matter whether we contract the MPO into a matrix or not, this inconsistent behavior already exists if we just print out `H`, and check the order of indexes for the first site `n=1`.

Is there any reason behind this designing pattern? Or actually I should not use `combiner()` in this way (given the order of indexes)?

thanks,
Taolin

Minimal Code
--------------
```
int N = 3;
auto t = 0.5;
auto mu = 0.1;
auto sites = Fermion(N);
auto ampo = AutoMPO(sites);

// Construct tight-binding AutoMPO
for (int i = 1; i <= N; ++i) {
  ampo += -mu, "N", i;
}

for (int i = 1; i < N; ++i) {
  ampo += -t, "Cdag", i, "C", i + 1;
  ampo += -t, "Cdag", i + 1, "C", i;
}
auto H = toMPO(ampo);   //  <---------- without using the argument {"Exact=", true}

// Re-construct the full Hamiltonian matrix from MPO
auto T = H(1) * H(2) * H(3);
auto idxs = inds(T);
PrintData(idxs);   //  <---------- print out the order of indexes

auto [Comb, c] = combiner(idxs[0], idxs[2], idxs[4]);
auto [Combp, cp] = combiner(idxs[1], idxs[3], idxs[5]);
auto mat = Comb * T * Combp;
```

Expected Result
-----------------
```
idxs = 
(dim=2|id=839|"n=1,Site,Fermion") <In>
  1: 1 QN({"Nf",0,-1})
  2: 1 QN({"Nf",1,-1})
(dim=2|id=839|"n=1,Site,Fermion")' <Out>
  1: 1 QN({"Nf",0,-1})
  2: 1 QN({"Nf",1,-1})
(dim=2|id=279|"n=2,Site,Fermion") <In>
  1: 1 QN({"Nf",0,-1})
  2: 1 QN({"Nf",1,-1})
(dim=2|id=279|"n=2,Site,Fermion")' <Out>
  1: 1 QN({"Nf",0,-1})
  2: 1 QN({"Nf",1,-1})
(dim=2|id=403|"n=3,Site,Fermion") <In>
  1: 1 QN({"Nf",0,-1})
  2: 1 QN({"Nf",1,-1})
(dim=2|id=403|"n=3,Site,Fermion")' <Out>
  1: 1 QN({"Nf",0,-1})
  2: 1 QN({"Nf",1,-1})
```

What I Actually Got
-------------------
Note that the difference is on `n=1`, which gives `<Out>`-ward bond first, followed by `<In>`-ward bond later.
```
idxs = 
(dim=2|id=341|"n=1,Site,Fermion")' <Out>
  1: 1 QN({"Nf",0,-1})
  2: 1 QN({"Nf",1,-1})
(dim=2|id=341|"n=1,Site,Fermion") <In>
  1: 1 QN({"Nf",0,-1})
  2: 1 QN({"Nf",1,-1})
(dim=2|id=630|"n=2,Site,Fermion") <In>
  1: 1 QN({"Nf",0,-1})
  2: 1 QN({"Nf",1,-1})
(dim=2|id=630|"n=2,Site,Fermion")' <Out>
  1: 1 QN({"Nf",0,-1})
  2: 1 QN({"Nf",1,-1})
(dim=2|id=4|"n=3,Site,Fermion") <In>
  1: 1 QN({"Nf",0,-1})
  2: 1 QN({"Nf",1,-1})
(dim=2|id=4|"n=3,Site,Fermion")' <Out>
  1: 1 QN({"Nf",0,-1})
  2: 1 QN({"Nf",1,-1})
```

**Comment by emstoudenmire** [comment]
Thanks for the question, however this behavior is considered correct in terms of the ITensor interface. The reason is that the high-level ITensor interface is *independent* of the ordering of the indices (https://www.scipost.org/SciPostPhysCodeb.4) so that the code is allowed to permute the indices into any order it wants, as long as the underlying data is also consistently permuted too. 

Of course you can (at a lower level) access the ITensor data in a way that depends on the index ordering, but when doing so you should always make such lines of code "safe" by explicitly permuting the indices into the order you expect.

Does that answer your question? If not, we can discuss further on the ITensor Discourse forum: https://itensor.discourse.group

**Comment by tanlin2013** [comment]
Thank you Miles for the answering!

I understand it's generally unnecessary to consider the order of indices. However in some applications, like the minimal example I gave above, I do need to group some indices, converting a higher-rank tensor back to the matrix. So as you suggested, I should always make such lines of code by explicitly permuting the indices into the order I want. 

But then I'm confused here, in ITensor, is there any way I could tell the `permute` function (or `combiner`) to distinguish the direction of indices, so I could group indices in different directions together? Because it appears like the inward and outward bond share the same tag name, and they only differ by the direction property. 

Or actually I have to implement this part on my own by calling the index property `dir(Index)`, and do some conditional check?

**Comment by mtfishman** [comment]
In this case it looks like you could group by prime levels.
