### ISSUE TITLE
use of variable length array in HermitianEigenvalues

### ISSUE THREAD

**Issue by kyungminlee** [ITensor/ITensor#79]
HermitianEigenvalues in utility.cc uses variable length arrays. They need to be replaced by std::vector. However, using static variables in this function and also functions in lapack_wrap.h breaks thread-safety. Is this not an issue?

**Comment by emstoudenmire** [comment]
Thanks for catching both of these issues. I agree about replacing all uses of variable length arrays with std::vector. I'll definitely do that in utility.cc as well. (As a note in the new version a lot of this older utility.cc code will be replaced by a massively cleaned up version.) I had not considered the thread safety of making the std::vectors static but I agree that's an important concern so I'll get rid of the static keyword for them.
