### ISSUE TITLE
global.h depends on unistd.h and mkdtemp (not supported in MSVC)

### ISSUE THREAD

**Issue by kyungminlee** [ITensor/ITensor#82]
global.h does not compile in MSVC, because of its dependence on unistd.h and mkdtemp. How about making a change to global.h as the following?

```C++
#if defined(_MSC_VER)
#include <process.h>
#include <io.h>
#include <direct.h>

inline char* mkdtemp(char *templat)
    {
    char* retval = _mktemp(templat);
    if (retval) { _mkdir(retval); }
    return retval;
    }
#else
#include <unistd.h>
#endif

```

**Comment by emstoudenmire** [comment]
Looks like a good suggestion. I don't have access to MSVC so I will have to take it at your word that this is a correct solution - please give it a try and let me know if there are any bugs in the implementation - thanks! In the new version I will spin this off as a separate utilities header for use by the MPS class and other objects that write to disk.
