### ISSUE TITLE
dscal declaration in matrixref.cc

### ISSUE THREAD

**Issue by kyungminlee** [ITensor/ITensor#84]
In `VectorRef & VectorRef::operator *= (Real a)` defined in `matrixref.cc`, is there a reason you declare `dscal` inside the method, or rather, why you define your own version of `dscal` in the first place? It causes linkage problem in MSVC, for instance when I try to compile tutorial `one.cc`.

```
matrix.lib(matrixref.obj) : error LNK2019: unresolved external symbol "void __cdecl dscal(int,double,double *,int)" (?dscal@@YAXHNPEANH@Z) referenced in function "public: class itensor::VectorRef & __cdecl itensor::VectorRef::operator*=(double)" (??XVectorRef@itensor@@QEAAAEAV01@N@Z)
```

 A quick fix would be to move the declaration outside, perhaps to line 62 together with `copyscale` and `dcopy`, or to use blas's `dscal_`.

**Comment by emstoudenmire** [comment]
Closing this issue for now, since we've completely replaced the MatrixRef layer of ITensor with a new layer. Please re-open this issue if the new version of the code is still causing a similar issue, thanks!
